/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradeselect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sanya
 */
public class FindTeacher extends javax.swing.JInternalFrame {
    private final String url = "jdbc:postgresql://localhost/grade";
    private final String user = "postgres";
    private final String password = "12345";
    
    private String lastname;
    private String firstname;
    private String secondname;
    private String SQL;
    public Connection connect() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }
    /**
     * Creates new form MyJInternalFrame2
     */
    public FindTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Поиск преподавателя");
        setPreferredSize(new java.awt.Dimension(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width - 10, java.awt.Toolkit.getDefaultToolkit().getScreenSize().height - 100));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setToolTipText("Введите Фамилию...");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setToolTipText("Введите Имя...");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setToolTipText("Введите отчество...");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Фамилия");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Имя");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Отчество");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Поиск");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Фамилия", "Имя", "Отчество", "Подразделение", "Должность"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lastname = jTextField1.getText();
        firstname = jTextField2.getText();
        secondname = jTextField3.getText();
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);
        if(!lastname.isEmpty() && !firstname.isEmpty() && !secondname.isEmpty()){
            SQL = "SELECT lastname, firstname, secondname, facultyname, jobpositionname FROM view_teachers where lastname = ? and firstname = ? and secondname = ? order by lastname";
        }
        if(lastname.isEmpty() && !firstname.isEmpty() && !secondname.isEmpty()){
            SQL = "SELECT lastname, firstname, secondname, facultyname, jobpositionname FROM view_teachers where firstname = ? and secondname = ? order by lastname";
        }
        if(!lastname.isEmpty() && firstname.isEmpty() && !secondname.isEmpty()){
            SQL = "SELECT lastname, firstname, secondname, facultyname, jobpositionname FROM view_teachers where lastname = ? and secondname = ? order by lastname";
        }
        if(!lastname.isEmpty() && !firstname.isEmpty() && secondname.isEmpty()){
            SQL = "SELECT lastname, firstname, secondname, facultyname, jobpositionname FROM view_teachers where lastname = ? and firstname = ? order by lastname";
        }
        if(!lastname.isEmpty() && firstname.isEmpty() && secondname.isEmpty()){
            SQL = "SELECT lastname, firstname, secondname, facultyname, jobpositionname FROM view_teachers where lastname = ? order by lastname";
        }
        if(lastname.isEmpty() && !firstname.isEmpty() && secondname.isEmpty()){
            SQL = "SELECT lastname, firstname, secondname, facultyname, jobpositionname FROM view_teachers where firstname = ? order by lastname";
        }
        if(lastname.isEmpty() && firstname.isEmpty() && !secondname.isEmpty()){
            SQL = "SELECT lastname, firstname, secondname, facultyname, jobpositionname FROM view_teachers where secondname = ? order by lastname";
        }
        try (var conn = this.connect();
            PreparedStatement pstmt = conn.prepareStatement(SQL)) {

            if(!lastname.isEmpty() && !firstname.isEmpty() && !secondname.isEmpty()){
                pstmt.setString(1,lastname);
                pstmt.setString(2,firstname);
                pstmt.setString(3,secondname);
            }
            if(lastname.isEmpty() && !firstname.isEmpty() && !secondname.isEmpty()){
                pstmt.setString(1,firstname);
                pstmt.setString(2,secondname);
            }
            if(!lastname.isEmpty() && firstname.isEmpty() && !secondname.isEmpty()){
                pstmt.setString(1,lastname);
                pstmt.setString(2,secondname);
            }
            if(!lastname.isEmpty() && !firstname.isEmpty() && secondname.isEmpty()){
                pstmt.setString(1,lastname);
                pstmt.setString(2,firstname);
            }
            if(!lastname.isEmpty() && firstname.isEmpty() && secondname.isEmpty()){
                pstmt.setString(1,lastname);
            }
            if(lastname.isEmpty() && !firstname.isEmpty() && secondname.isEmpty()){
                pstmt.setString(1,firstname);
            }
            if(lastname.isEmpty() && firstname.isEmpty() && !secondname.isEmpty()){
                pstmt.setString(1,secondname);
            }

            ResultSet rs = pstmt.executeQuery();

            // jTable1.remov;
            while (rs.next()) {
                String lstnm = rs.getString("lastname");
                String frstnm = rs.getString("firstname");
                String scndnm = rs.getString("secondname");
                String dep = rs.getString("facultyname");
                String job = rs.getString("jobpositionname");

                String tbData[] = {lstnm,frstnm,scndnm,dep, job};
                tblModel.addRow(tbData);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
