/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradeselect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sanya
 */
public class TeachersListByFaculty extends javax.swing.JInternalFrame {
    private final String url = "jdbc:postgresql://localhost/grade";
    private final String user = "postgres";
    private final String password = "12345";
    
    private String facultyname;
    public Connection connect() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }
    /**
     * Creates new form MyJInternalFrame2
     */
    public TeachersListByFaculty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FacultyName = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Список сотрудников подразделения");
        setPreferredSize(new java.awt.Dimension(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width - 10, java.awt.Toolkit.getDefaultToolkit().getScreenSize().height - 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Подразделение ЮФУ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        FacultyName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Институт философии и социально-политических наук", "Институт радиотехнических систем и управления", "Факультет бизнеса \"Капитаны\"", "Научно-образовательный центр \"Международный центр образования и иберо-американских исследований ЮФУ\"", "Учебный военный центр", "Филиал ЮФУ в г. Новошахтинск", "Академия психологии и педагогики", "Институт высоких технологий и пьезотехники", "Факультет управления", "Институт управления в экономических, экологических и социальных системах", "Научно-исследовательский институт физической и органической химии", "Институт нанотехнологий, электроники и приборостроения", "Институт компьютерных технологий и информационной безопасности", "Юридический факультет", "Физический факультет", "Институт военного обучения", "Институт филологии, журналистики и межкультурной коммуникации", "Международный институт междисциплинарного образования и иберо-американских исследований", "Академия физической культуры и спорта", "Академия биологии и биотехнологии", "Инженерно-технологическая академия", "Факультет военного обучения", "Южный федеральный университет", "Академия архитектуры и искусств", "МИЦ «Интеллектуальные материалы»", "Институт наук о Земле", "ЦНИ «Инструментальные, математические и интеллектуальные средства в экономике»", "Институт социологии и регионоведения", "Филиал ЮФУ в г. Геленджике", "Высшая школа бизнеса", "Экономический факультет", "Институт математики, механики и компьютерных наук", "Международный исследовательский институт интеллектуальных материалов ЮФУ", "Научно-исследовательский институт нейрокибернетики", "Химический факультет", "Институт истории и международных отношений", "Иберо-Американское отделение", "Научно-исследовательский институт физики" }));
        FacultyName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FacultyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyNameActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Показать");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Фамилия", "Имя", "Отчество", "Должность"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FacultyName, 0, 181, Short.MAX_VALUE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FacultyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultyNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        facultyname = FacultyName.getSelectedItem().toString();
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);

        String SQL = "SELECT distinct lastname, firstname, secondname, jobpositionname FROM view_teachers where facultyname = ? order by lastname";
        try (Connection conn = this.connect();
            PreparedStatement pstmt = conn.prepareStatement(SQL)) {

            pstmt.setString(1,facultyname);
            ResultSet rs = pstmt.executeQuery();

            // jTable1.remov;
            while (rs.next()) {
                String lstnm = rs.getString("lastname");
                String frstnm = rs.getString("firstname");
                String scndnm = rs.getString("secondname");
                String job = rs.getString("jobpositionname");

                String tbData[] = {lstnm,frstnm,scndnm,job};
                tblModel.addRow(tbData);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FacultyName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
